"""add last_activity_at and closed status

Revision ID: 06b31e51f9be
Revises: c9cfe3e19441
Create Date: 2026-02-25 18:43:01.546840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b31e51f9be'
down_revision: Union[str, None] = 'c9cfe3e19441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
