"""add last_activity to conversations

Revision ID: 09dcbe4d052c
Revises: 9d15effb5e6b
Create Date: 2026-02-25 17:07:28.544372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09dcbe4d052c'
down_revision: Union[str, None] = '9d15effb5e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_conversations_status_last_activity', 'conversations', ['status', 'last_activity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_conversations_status_last_activity', table_name='conversations')
    op.drop_column('conversations', 'last_activity')
    # ### end Alembic commands ###
