"""add last_activity_at to conversations

Revision ID: c9cfe3e19441
Revises: e5465a7f14ea
Create Date: 2026-02-25 18:41:16.639333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9cfe3e19441'
down_revision: Union[str, None] = 'e5465a7f14ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
