"""add last_activity_at to conversations

Revision ID: d185cb705a09
Revises: 26e67a2f0236
Create Date: 2026-02-25 19:11:21.569346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd185cb705a09'
down_revision: Union[str, None] = '26e67a2f0236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
