"""add last_activity_at to conversations

Revision ID: e5465a7f14ea
Revises: 09dcbe4d052c
Create Date: 2026-02-25 17:45:41.487086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5465a7f14ea'
down_revision: Union[str, None] = '09dcbe4d052c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_index('ix_conversations_status_last_activity', table_name='conversations')
    op.drop_column('conversations', 'last_activity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('last_activity', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index('ix_conversations_status_last_activity', 'conversations', ['status', 'last_activity'], unique=False)
    op.drop_column('conversations', 'last_activity_at')
    # ### end Alembic commands ###
